recipe: lagoon
config:
  flavor: drupal
env_file:
  - .env
  - .lagoon.env

services:
  appserver:
    webroot: web
    type: php:8.2
    build_as_root:
      - mkdir -p /root/tmp
      - chmod 666 /root/tmp
      - mkdir -p /app/web/sites/simpletest/browser-output
      - chmod 777 -R /app/web/sites/simpletest
      - /usr/local/bin/composer self-update
    overrides:
      environment:
        PHP_IDE_CONFIG: serverName=localhost
        XDEBUG_MODE: debug
        XDEBUG_SESSION: PHPSTORM
      volumes:
        - ${HOME}/.lando/composer_cache:/var/www/.composer

