recipe: lagoon
config:
  flavor: drupal
env_file:
  - .lagoon.env

services:
  appserver:
    webroot: web
    type: php:8.2
    overrides:
      environment:
        PHP_IDE_CONFIG: serverName=localhost
        XDEBUG_MODE: debug
        XDEBUG_SESSION: PHPSTORM
      volumes:
        - ${HOME}/.lando/composer_cache:/var/www/.composer

